"""add learning behavior features tables

Revision ID: 20260301_170000
Revises: previous_revision_id
Create Date: 2026-03-01 17:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20260301_170000"
down_revision = "010_create_sponsorship_tables"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建学习行为特征表
    op.create_table(
        "learning_behavior_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("context_id", sa.String(length=100), nullable=True),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("debug_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("debug_attempts", sa.Integer(), nullable=True),
        sa.Column("breakpoints_used", sa.Integer(), nullable=True),
        sa.Column("debug_commands_executed", sa.Integer(), nullable=True),
        sa.Column("error_types_encountered", sa.Text(), nullable=True),
        sa.Column("hardware_operation_success_rate", sa.Float(), nullable=True),
        sa.Column("hardware_operations_count", sa.Integer(), nullable=True),
        sa.Column("successful_operations", sa.Integer(), nullable=True),
        sa.Column("failed_operations", sa.Integer(), nullable=True),
        sa.Column("hardware_types_used", sa.Text(), nullable=True),
        sa.Column("hardware_connection_duration", sa.Integer(), nullable=True),
        sa.Column("success_indicator", sa.Boolean(), nullable=True),
        sa.Column("performance_score", sa.Float(), nullable=True),
        sa.Column("difficulty_level", sa.String(length=20), nullable=True),
        sa.Column("help_requested", sa.Boolean(), nullable=True),
        sa.Column("hints_used", sa.Integer(), nullable=True),
        sa.Column("platform", sa.String(length=50), nullable=True),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("browser_info", sa.String(length=200), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=True),
        sa.Column("processing_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # 创建索引
    op.create_index(
        "idx_behavior_student_category",
        "learning_behavior_features",
        ["student_id", "category"],
    )
    op.create_index(
        "idx_behavior_timestamp", "learning_behavior_features", ["event_timestamp"]
    )
    op.create_index(
        "idx_behavior_context",
        "learning_behavior_features",
        ["context_id", "session_id"],
    )
    op.create_index(
        "idx_behavior_org_student",
        "learning_behavior_features",
        ["org_id", "student_id"],
    )
    op.create_index(
        op.f("ix_learning_behavior_features_category"),
        "learning_behavior_features",
        ["category"],
    )
    op.create_index(
        op.f("ix_learning_behavior_features_context_id"),
        "learning_behavior_features",
        ["context_id"],
    )
    op.create_index(
        op.f("ix_learning_behavior_features_created_at"),
        "learning_behavior_features",
        ["created_at"],
    )
    op.create_index(
        op.f("ix_learning_behavior_features_event_timestamp"),
        "learning_behavior_features",
        ["event_timestamp"],
    )
    op.create_index(
        op.f("ix_learning_behavior_features_event_type"),
        "learning_behavior_features",
        ["event_type"],
    )
    op.create_index(
        op.f("ix_learning_behavior_features_id"), "learning_behavior_features", ["id"]
    )
    op.create_index(
        op.f("ix_learning_behavior_features_org_id"),
        "learning_behavior_features",
        ["org_id"],
    )
    op.create_index(
        op.f("ix_learning_behavior_features_session_id"),
        "learning_behavior_features",
        ["session_id"],
    )
    op.create_index(
        op.f("ix_learning_behavior_features_student_id"),
        "learning_behavior_features",
        ["student_id"],
    )

    # 创建学习行为汇总表
    op.create_table(
        "learning_behavior_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("period_type", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("total_debug_duration", sa.Integer(), nullable=True),
        sa.Column("avg_debug_duration", sa.Float(), nullable=True),
        sa.Column("debug_sessions_count", sa.Integer(), nullable=True),
        sa.Column("total_debug_attempts", sa.Integer(), nullable=True),
        sa.Column("total_hardware_operations", sa.Integer(), nullable=True),
        sa.Column("successful_hardware_operations", sa.Integer(), nullable=True),
        sa.Column("hardware_success_rate", sa.Float(), nullable=True),
        sa.Column("unique_hardware_types", sa.Integer(), nullable=True),
        sa.Column("lessons_completed", sa.Integer(), nullable=True),
        sa.Column("exercises_attempted", sa.Integer(), nullable=True),
        sa.Column("exercises_completed", sa.Integer(), nullable=True),
        sa.Column("average_performance_score", sa.Float(), nullable=True),
        sa.Column("help_requests_count", sa.Integer(), nullable=True),
        sa.Column("hints_used_count", sa.Integer(), nullable=True),
        sa.Column("collaboration_events", sa.Integer(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # 创建汇总表索引
    op.create_index(
        "idx_summary_student_period",
        "learning_behavior_summaries",
        ["student_id", "period_type", "period_start"],
    )
    op.create_index(
        "idx_summary_org_period",
        "learning_behavior_summaries",
        ["org_id", "period_type", "period_start"],
    )
    op.create_index(
        op.f("ix_learning_behavior_summaries_id"), "learning_behavior_summaries", ["id"]
    )
    op.create_index(
        op.f("ix_learning_behavior_summaries_org_id"),
        "learning_behavior_summaries",
        ["org_id"],
    )
    op.create_index(
        op.f("ix_learning_behavior_summaries_period_start"),
        "learning_behavior_summaries",
        ["period_start"],
    )
    op.create_index(
        op.f("ix_learning_behavior_summaries_period_type"),
        "learning_behavior_summaries",
        ["period_type"],
    )
    op.create_index(
        op.f("ix_learning_behavior_summaries_student_id"),
        "learning_behavior_summaries",
        ["student_id"],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除索引
    op.drop_index("idx_summary_org_period", table_name="learning_behavior_summaries")
    op.drop_index(
        "idx_summary_student_period", table_name="learning_behavior_summaries"
    )
    op.drop_index(
        op.f("ix_learning_behavior_summaries_student_id"),
        table_name="learning_behavior_summaries",
    )
    op.drop_index(
        op.f("ix_learning_behavior_summaries_period_type"),
        table_name="learning_behavior_summaries",
    )
    op.drop_index(
        op.f("ix_learning_behavior_summaries_period_start"),
        table_name="learning_behavior_summaries",
    )
    op.drop_index(
        op.f("ix_learning_behavior_summaries_org_id"),
        table_name="learning_behavior_summaries",
    )
    op.drop_index(
        op.f("ix_learning_behavior_summaries_id"),
        table_name="learning_behavior_summaries",
    )

    op.drop_index("idx_behavior_org_student", table_name="learning_behavior_features")
    op.drop_index("idx_behavior_context", table_name="learning_behavior_features")
    op.drop_index("idx_behavior_timestamp", table_name="learning_behavior_features")
    op.drop_index(
        "idx_behavior_student_category", table_name="learning_behavior_features"
    )
    op.drop_index(
        op.f("ix_learning_behavior_features_student_id"),
        table_name="learning_behavior_features",
    )
    op.drop_index(
        op.f("ix_learning_behavior_features_session_id"),
        table_name="learning_behavior_features",
    )
    op.drop_index(
        op.f("ix_learning_behavior_features_org_id"),
        table_name="learning_behavior_features",
    )
    op.drop_index(
        op.f("ix_learning_behavior_features_id"),
        table_name="learning_behavior_features",
    )
    op.drop_index(
        op.f("ix_learning_behavior_features_event_type"),
        table_name="learning_behavior_features",
    )
    op.drop_index(
        op.f("ix_learning_behavior_features_event_timestamp"),
        table_name="learning_behavior_features",
    )
    op.drop_index(
        op.f("ix_learning_behavior_features_created_at"),
        table_name="learning_behavior_features",
    )
    op.drop_index(
        op.f("ix_learning_behavior_features_context_id"),
        table_name="learning_behavior_features",
    )
    op.drop_index(
        op.f("ix_learning_behavior_features_category"),
        table_name="learning_behavior_features",
    )

    # 删除表
    op.drop_table("learning_behavior_summaries")
    op.drop_table("learning_behavior_features")

    # ### end Alembic commands ###
