name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Backend Docker image
      run: docker build . --file Dockerfile.backend --tag openmtscied-backend:$(date +%s)

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Frontend Docker image
      run: docker build . --file Dockerfile.frontend --tag openmtscied-frontend:$(date +%s)
